name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: |
          npm install --frozen-lockfile
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Pages Action"
          npm run deploy
        working-directory: docs
        env:
          GIT_USER: ${{ secrets.ACCESS_TOKEN }}
